# Generated by Django 4.2.10 on 2024-03-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
