# Generated by Django 4.2.10 on 2024-03-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hostel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['name']},
        ),
    ]
