# Generated by Django 4.2.10 on 2024-03-21 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hostelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
