# Generated by Django 4.2.10 on 2024-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hostelimage_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelimage',
            name='image',
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
