# Generated by Django 4.2.10 on 2024-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_hostelimage_image_hostelimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.FloatField(default=-1.5716, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.FloatField(default=6.67474, null=True),
        ),
    ]
