# Generated by Django 4.2.10 on 2024-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_hostel_latitude_hostel_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
