# Generated by Django 4.2.10 on 2024-05-09 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_booking_bookingitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingitem",
            name="unit_price",
        ),
        migrations.AlterField(
            model_name="room",
            name="available_beds",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
